<?php

/**
 * @file
 * Contains addressfield_cr.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function addressfield_cr_help($route_name, RouteMatchInterface $route_match) {

}

/**
 *
 */
function getProvinces() {
  $result = [];
  $addresses = getAddresses();

  foreach ($addresses as $province => $province_cantons) {
    $result[$province] = $province;
  }

  return $result;
}

/**
 *
 */
function getCantons($province_name) {
  $result = [];
  $addresses = getAddresses();

  foreach ($addresses as $province => $province_cantons) {
    foreach ($province_cantons as $canton => $canton_districts) {
      if ($province == $province_name) {
        $result[$canton] = $canton;
      }
    }
  }

  return $result;
}

/**
 *
 */
function getDistricts($canton_name) {
  $result = [];
  $addresses = getAddresses();

  foreach ($addresses as $province => $province_cantons) {
    foreach ($province_cantons as $canton => $canton_districts) {
      foreach ($canton_districts as $district => $postal_code) {
        if ($canton == $canton_name) {
          $result[$district] = $district;
        }
      }
    }
  }

  return $result;
}

/**
 *
 */
function getZIPCodeByDistrict($district_name, $canton_name) {
  $result = "";
  $addresses = getAddresses();

  foreach ($addresses as $province => $province_cantons) {
    foreach ($province_cantons as $canton => $canton_districts) {
      foreach ($canton_districts as $district => $postal_code) {
        if ($district == $district_name && $canton == $canton_name) {
          $result = $postal_code;
          break;
        }
      }
    }
  }

  return $result;
}

/**
 *
 */
function getAddressByZIPCode($zip_code) {
  $result = [];
  $addresses = getAddresses();

  foreach ($addresses as $province => $province_cantons) {
    foreach ($province_cantons as $canton => $canton_districts) {
      foreach ($canton_districts as $district => $zip_code_district) {
        if ($zip_code == $zip_code_district) {
          // $result = $province . '-' . $canton . '-' . $district;.
          $result['province'] = $province;
          $result['canton'] = $canton;
          $result['district'] = $district;
          break;
        }
      }
    }
  }

  return $result;
}

/**
 *
 */
function getAddresses() {
  return json_decode(
        file_get_contents(dirname(__FILE__) . '/zips.json'),
        TRUE
  );
}
